# https://golangci-lint.run/usage/quick-start/
run:
  timeout: 12m
  skip-dirs:
    - vendor
linters:
  enable:
    - bodyclose
    - errcheck
    - goimports
    - exportloopref
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unparam
    - unused
linters-settings:
  goimports:
    local-prefixes: product-management
  gosec:
    includes:
      - G304
      - G307
    excludes:
      # G106: Use of ssh InsecureIgnoreHostKey should be audited
      - G106
      # G402: TLS InsecureSkipVerify set true
      - G402
      # G601: Implicit memory aliasing in for loop.
      - G601
