version: "3"
services:
  mysql:
    image: mysql:5.7.38
    container_name: mysql5.7
    environment:
      MYSQL_DATABASE: productmgm
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      TZ: Asia/Seoul
      LANG: C.UTF-8
    volumes:
      - /tmp/mysql_data:/var/lib/mysql
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake'
    ports:
      - "3306:3306"