version: "3"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.38
    container_name: mysql5.7
    environment:
      MYSQL_DATABASE: productmgm
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      TZ: Asia/Seoul
    volumes:
      - /tmp/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"